# Generated by Django 4.0.4 on 2022-04-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='studentNum',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
