# Generated by Django 4.0.4 on 2022-04-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_club_rename_studentnum_user_id_remove_user_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
