# Generated by Django 4.0.4 on 2022-04-19 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_history_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='clubName',
            field=models.ForeignKey(db_column='clubName', on_delete=django.db.models.deletion.CASCADE, to='app.club'),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='position',
            field=models.CharField(blank=True, default='회장', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
